### PR TITLE
Update github stuff + correct tiny errors.

### PR DESCRIPTION
**Pull request by Kichura**
Title explains it all - Although a portion was copied over from the wildfire's gender mod as it is faster,

I cannot add the short description to the about box to middle-right of repository as only collaborators can.

*(edits are welcomed)*

### CODE REVIEW

**Comment by Kichura** [comment]
The nightVisionFlashingFix text was renamed because it sounded a bit wrong imo - This one should clarify it but idk if the config itself will replace the old one.

**Review by Kichura — COMMENTED** [review]
This was upstreamed as the es_ES file became merged along with an trinkets fix being pushed out.

**Review by Kichura — COMMENTED** [review]
i put the icon to wrong folder after all - did it correctly this time.

**Comment by ThatPreston** [comment]
I appreciate the effort you put into making all of these small changes, but I find most of them to be unnecessary.
- I think putting the license in every file is unneeded and makes things feel cluttered. Not to mention if I ever decided to change it I would have to update every file.
- I am fine with the current name of the night vision flashing config option, enough said there.
- I have no idea what you did to the .gitignore and workflow files, and they work fine as is, so I don't see the point in changing them. I am relatively new to github and I would prefer to make these changes myself if the need arises instead of having it done for me.
- I updated the README.md file myself yesterday, so that is already done.
- As for the updates to gradle and JDK, I will make a mental note to fix those before I release 2.1.

With all of those things said, I am going to close this pull request. Thanks again for taking an interest in improving the mod, it is appreciated.

**Comment by Kichura** [comment]
The github workflow was designed to build a new mod copy on every commit which is mostly done for testing reasons which includes certain patches such as update the OS and whatnot, the gitignore part was morely done as a clean-up attempt to prevent unwanted data from being included in the ZIP archive - And finally; the licensing part was partially manatory in specific licenses such as GPLv3 which i did add at the end.

As for the commits that are important to you - Feel free to cherrypick them although this is probably all i can output from the last context.

As for the fork itself as a whole - Wiped, the end.

**Pull request closed without merging**
